mkdir fedtask

ROUND=400
EPOCH_PER_ROUND=8
PROPOTION=0.2
NUM_CLIENT=30
K=6

CUDA_VISIBLE_DEVICES=1,0 python main.py --task cifar10_cluster_sparse_scaffold_N${NUM_CLIENT}_K${K} --wandb 0 --model resnet9 --algorithm scaffold_with_random --data_folder ./benchmark/cifar10/data --log_folder fedtask --dataidx_filename cifar10/cluster_sparse/${NUM_CLIENT}client/cifar10_cluster_sparse.json --num_rounds ${ROUND}  --num_epochs ${EPOCH_PER_ROUND} --proportion ${PROPOTION} --batch_size 10 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=1,0 python main.py --task cifar10_cluster_sparse_scaffold_N${NUM_CLIENT}_K${K} --wandb 0 --model resnet9 --algorithm scaffold --data_folder ./benchmark/cifar10/data --log_folder fedtask --dataidx_filename cifar10/cluster_sparse/${NUM_CLIENT}client/cifar10_cluster_sparse.json --num_rounds ${ROUND}  --num_epochs ${EPOCH_PER_ROUND} --proportion ${PROPOTION} --batch_size 10 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=1,0 python main.py --task cifar10_cluster_sparse_scaffold_N2000_K50 --wandb 1 --model resnet9 --algorithm scaffold_with_cluster --data_folder ./benchmark/cifar10/data --log_folder fedtask --dataidx_filename cifar10/cluster_sparse/2000client/cifar10_cluster_sparse.json --num_rounds ${ROUND}  --num_epochs ${EPOCH_PER_ROUND} --proportion ${PROPOTION} --batch_size 2 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=1,0 python main.py --task cifar10_sparse_N500_K20 --wandb 0 --model resnet9 --algorithm feddyn --data_folder ./benchmark/cifar100/data --log_folder fedtask --dataidx_filename cifar100/cluster_sparse/500client/cifar100_sparse.json --num_rounds 20000 --num_epochs 8 --proportion 0.04 --batch_size 4 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# CUDA_VISIBLE_DEVICES=1,0 python main.py --task mnist_cluster_sparse_scaffold_N50_K50_E8 --wandb 1 --model cnn --algorithm scaffold_with_cluster  --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/cluster_sparse/50client/mnist_cluster_sparse.json --num_rounds ${ROUND}  --num_epochs ${EPOCH_PER_ROUND} --proportion ${PROPOTION} --batch_size 2 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=1,0 python main.py --task mnist_cluster_sparse_scaffold_N50_K50_E8 --wandb 1 --model cnn --algorithm scaffold_with_random  --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/cluster_sparse/50client/mnist_cluster_sparse.json --num_rounds ${ROUND}  --num_epochs ${EPOCH_PER_ROUND} --proportion ${PROPOTION} --batch_size 2 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=1,0 python main.py --task mnist_cluster_sparse_scaffold_N50_K50_E8 --wandb 1 --model cnn --algorithm scaffold  --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/cluster_sparse/50client/mnist_cluster_sparse.json --num_rounds ${ROUND}  --num_epochs ${EPOCH_PER_ROUND} --proportion ${PROPOTION} --batch_size 2 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0